---
title: "qPCR_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Get dependencies
```{r}
## get dependencies
library(tidyverse)
library(scales)
library(here)
```

Write plotting functions

Function 1: a set of functions to squash the y axis from this source:
https://rpubs.com/huanfaChen/squash_remove_y_axix_ggplot#:~:text=In%20ggplot%3A%20squash%2Fremove%20part%20of%20y%2Daxis&text=If%20one%20wants%20to%20squash,use%20the%20facet_grid()%20function

```{r}
squash_axis <- function(from, to, factor) { 
    # A transformation function that squashes the range of [from, to] by factor on a given axis 

    # Args:
    #   from: left end of the axis
    #   to: right end of the axis
    #   factor: the compression factor of the range [from, to]
    #
    # Returns:
    #   A transformation called "squash_axis", which is capsulated by trans_new() function

  trans <- function(x) {    
      # get indices for the relevant regions
      isq <- x > from & x < to & !is.na(x)
      ito <- x >= to & !is.na(x)

      # apply transformation
      x[isq] <- from + (x[isq] - from)/factor
      x[ito] <- from + (to - from)/factor + (x[ito] - to)

      return(x)
  }

  inv <- function(x) {

      # get indices for the relevant regions
      isq <- x > from & x < from + (to - from)/factor & !is.na(x)
      ito <- x >= from + (to - from)/factor & !is.na(x)

      # apply transformation
      x[isq] <- from + (x[isq] - from) * factor
      x[ito] <- to + (x[ito] - (from + (to - from)/factor))

      return(x)
  }

# return the transformation
  return(trans_new("squash_axis", trans, inv))
}
```


Function 2: Percent RNA across the gradient
```{r}
## % RNA function
gene_plot.percrna <- function(df = df, gene_ = "Actb", fractions = 20, condition_ = "scr|eIF4E1|eIF4G|Larp1", colors = c("darkorange4", "darkorange3", "darkorange2", "darkorange1", "orange"), squash_from = 0, squash_to = 1, squash_factor = 1, ylim_ = c(0,50), y.breaks = 10, folder = "20220601_qPCR", y_axis = c(0,0.5), outfile = "plot.pdf", save = "y") {
        
        quartiles <- c(seq(from = 1, to = fractions - 1, by = 1))
        x_int <- quartiles + 0.5
        
        geneplot <- df %>% filter(gene == gene_) %>%
                filter(grepl(condition_, condition)) %>% 
                ggplot(aes(fraction, mean, group = interaction(gene, condition))) +
                        geom_line(aes(color = condition), linewidth = 1) +
                        geom_point(aes(color = condition)) +
                        geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.25) +
                        theme_classic() +
                        geom_vline(xintercept = x_int, linetype = "dashed", alpha = 1) +
                        labs(title = gene_,
                             y = "% RNA",
                             x = "Fraction") +
                        scale_color_manual(values = colors) +
                        coord_cartesian(ylim = ylim_) +
                        theme(axis.title.x = element_text(size=20),
                              axis.title.y = element_text(size=20),
                              axis.text.x = element_text(size=12),
                              axis.text.y = element_text(size=16),
                              legend.title = element_text(size=16),
                              legend.text = element_text(size=18),
                              title = element_text(size=18)) +
                        scale_x_continuous(breaks = c(1:n_distinct(df[["fraction"]]))) +
                        scale_y_continuous(breaks = seq(ylim_[[1]], ylim_[[2]], by = y.breaks), trans = squash_axis(squash_from, squash_to, squash_factor))
                        
         if(save == "y"){
                 ggsave(filename = here(folder, outfile), plot = geneplot, device = "pdf")
        }
        
        print(geneplot)
        
}

## example
## gene_plot.percrna(df = df.percrna, gene_ = "Actb", fractions = 20, condition_ = "scr|eIF4E", colors = c("darkorange4", "darkorange3", "darkorange2", "darkorange1", "orange"), folder = "qPCR", outfile = "Actb.pdf", save = "n")
```


Import % RNA data
```{r}
# import excel data from clipboard (in other words, copy the desired cells in excel and run the following code)
# my_data <- read.table(pipe("pbpaste"), sep="\t", header = TRUE)

if(!file.exists(here("qPCR", "R_csv_files", "20231019_combined-analysis.csv"))) {
          df.percrna <- read.table(pipe("pbpaste"), sep="\t", header = TRUE)
          as_tibble(df.percrna)
          write.csv(df.percrna, here("qPCR", "R_csv_files", "20231019_combined-analysis.csv"), row.names = FALSE)
} else {
          df.percrna <- read_csv(here("qPCR", "R_csv_files", "20231019_combined-analysis.csv"))
}

```

Reformat data
```{r}
if(!file.exists(here("qPCR", "R_csv_files", "20231019_combined-analysis_formatted.csv"))) {

df.percrna <- df.percrna %>% select(1:length(colnames(df.percrna))) %>% pivot_longer(3:length(colnames(df.percrna)), names_sep = "_", names_to = c("condition", "fraction"), values_to = "value") %>% group_by(interaction(gene, condition, fraction)) %>% drop_na()

stats.percrna <- df.percrna %>% group_by(interaction(gene, condition, fraction)) %>%
          summarize(mean = mean(value, na.rm = TRUE), 
                    sd = sd(value, na.rm = TRUE)) %>%
          mutate(lower = mean - sd, 
                 upper = mean + sd)

df.percrna <- df.percrna %>% full_join(stats.percrna) %>% filter(rep == 1) %>% select(-rep)

df.percrna[["fraction"]] <- as.numeric(df.percrna[["fraction"]])

write.csv(df.percrna, here("qPCR", "R_csv_files", "20231019_combined-analysis_formatted.csv"), row.names = FALSE)

} else {
        df.percrna <- read_csv(here("qPCR", "R_csv_files", "20231019_combined-analysis_formatted.csv"))
}

```


Plot % RNA data
```{r}
## example
gene_plot.percrna(df = df.percrna, gene_ = "Myc", fractions = 8, condition_ = "UT|Torin|Silv|Arsenite|Puro30|", colors = c("Blue", "Pink1", "Orange", "Green","Black"), ylim_ = c(0, 65), y.breaks = 5, squash_from = 10, squash_to = 85, squash_factor = 1, folder = "qPCR/plots", outfile = "20231019_Myc.pdf", save = "n")
```
